spring:
  application:
    name: gastro-link-api
  datasource:
    url: "jdbc:mysql://localhost:3306/gastro_link"
    username: myuser
    password: secret
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true

jwt:
  secret: ktPxSfQgtSLg02U1gcWpynSEXouD3wELKuMdiMt86VE=
  expiration: 28800000 # 8 horas em milissegundos